version: '{build}'

clone_depth: 50

cache:
  - '%LOCALAPPDATA%\Microsoft\dotnet -> appveyor.yml'
  - '%USERPROFILE%\.nuget\packages -> appveyor.yml, **\project.json, Nuget.Config'

before_build:
  # Install dotnet cli
  - appveyor DownloadFile https://raw.githubusercontent.com/dotnet/cli/rel/1.0.1/scripts/obtain/dotnet-install.ps1
  - powershell -File dotnet-install.ps1
  - set PATH=%PATH%;%LOCALAPPDATA%\Microsoft\dotnet
  - dotnet --version

  # Restore packages
  - dotnet restore .\src\EntryPoint
  - dotnet restore .\test\EntryPointTests

build_script:
  - dotnet build .\src\EntryPoint
  - dotnet build .\test\EntryPointTests

test_script:
  # .NET Core
  - dotnet test .\test\EntryPointTests

after_test:
  - dotnet pack .\src\EntryPoint --configuration=Release --output=".\Nuget"

artifacts:
  - path: .\src\EntryPoint\Nuget\*.nupkg