using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EntryPoint.OptionModel {
    internal static class HelpGenerator {

        // Given a Model, generates a string which can be printed to the CLI 
        // based on information provided by the ApplicationModel
        public static string Generate(Model model) {
            StringBuilder builder = new StringBuilder();

            if (model.ApplicationOptions.UtilityName.Length > 0) {
                builder.AppendLine(model.ApplicationOptions.UtilityName);
                builder.AppendLine();
            }
            if (model.Help.Detail.Length > 0) {
                builder.AppendLine(model.Help.Detail);
                builder.AppendLine();
            }
            foreach (var option in model) {
                string o = $"   -{option.Definition.SingleDashChar} --{option.Definition.DoubleDashName}"
                         + $"{option.Help.Detail}";
                builder.AppendLine(o);
                builder.AppendLine();
            }
            builder.AppendLine("Generated by EntryPoint");

            return builder.ToString();
        }
    }

}
