using EntryPoint.Parsing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EntryPoint.OptionModel {
    internal static class Help {
        public static void HandleHelpRequest(Model model) {
            var help = Generate(model);
            Console.WriteLine(help);
            Console.WriteLine("\nPress Enter to exit...");
            Console.ReadLine();
            Environment.Exit(0);
        }

        // Given a Model, generates a string which can be printed to the CLI 
        // based on information provided by the ApplicationModel
        public static string Generate(Model model) {
            StringBuilder builder = new StringBuilder();
            
            if (model.ApplicationOptions.UtilityName.Length > 0) {
                builder.AppendLine(model.ApplicationOptions.UtilityName);
                builder.AppendLine();
            }
            if (model.Help.Detail.Length > 0) {
                builder.AppendLine(model.Help.Detail);
                builder.AppendLine();
            }
            
            foreach (var option in model.OrderBy(mo => mo.Definition.ShortName)) {
                builder.AppendLine($"   -{option.Definition.ShortName} --{option.Definition.LongName}");
                builder.AppendLine($"   {option.Help.Detail}");
                builder.AppendLine();
            }
            builder.AppendLine("Generated by EntryPoint");

            return builder.ToString();
        }
    }

}
